disablePathToLower = true
languageCode = "en-us"
disqusShortname = "gsorasplace"
title = "gsora's place"
baseurl = "http://blog.gsora.xyz"
canonifyurls = true
theme = "poole-gsora"

[permalinks]
  post = "/:title/"
