disablePathToLower = true
languageCode = "en-us"
disqusShortname = "gsorasplace"
title = "gsora's place"
baseurl = "https://blog.gsora.xyz"
canonifyurls = true
theme = "poole-gsora"
#pygmentsCodeFences = true commented out until i fix my template
[permalinks]
  post = "/:title/"
