disablePathToLower = true
languageCode = "en-us"
#disqusShortname = "gsorasplace"
title = "gsora's place"
baseurl = "https://blog.gsora.xyz"
canonifyurls = true
theme = "poole-gsora"
rssLimit = 3
#pygmentsCodeFences = true commented out until i fix my template
pygmentsCodeFences = true
[permalinks]
  post = "/:title/"
