# theme.toml template for a Hugo theme

name = "Poolora"
license = "MIT"
licenselink = "https://github.com/gsora/poolora/blob/master/LICENSE.md"
description = "A port of my custom Poole distribution, for Hugo."
homepage = "http://siteforthistheme.com/"
tags = ["minimal", "responsive"]
features = ["", ""]
min_version = 0.17

[author]
  name = "Gianguido (gsora) Sorà"
  homepage = "https://me.gsora.xyz"
